#11426 dashboard
abpframework/eShopOnAbp pull request #110
Opened 2022-04-28 07:31 UTC by mahmut-gundogdu

Ordering dashboard implemented

2022-05-04 20:59 UTC, gterdem requested changes

2022-05-04 20:59 UTC, gterdem commented on services/ordering/src/EShopOnAbp.OrderingService.EntityFrameworkCore/EShopOnAbp.OrderingService.EntityFrameworkCore.csproj
> +    <ProjectReference Include="..\EShopOnAbp.OrderingService.Application.Contracts\EShopOnAbp.OrderingService.Application.Contracts.csproj" />
This is not correct. See my comment for `OrderingServiceRemoteServiceConsts`.

2022-05-04 20:59 UTC, gterdem commented on services/ordering/src/EShopOnAbp.OrderingService.Application.Contracts/OrderingServiceRemoteServiceConsts.cs
> +        public const int Top10 = 10;
This is the wrong layer. Constants should be under Domain.Shared especially when you are planning to use them on EntityFrameworkCore layer.

2022-05-05 12:44 UTC, gterdem approved these changes

2022-05-09 13:25 UTC, muhammedaltug commented on apps/angular/projects/ordering/src/pages/dashboard/components/order-status-chart/order-status-chart.component.ts
> +        label: 'Order Statuses',
label needs translation

2022-05-09 13:25 UTC, muhammedaltug commented on apps/angular/projects/ordering/src/pages/dashboard/components/payments-chart/payments-chart.component.ts
> +        label: 'Order Statuses',
label needs translation

2022-05-09 13:25 UTC, muhammedaltug commented on apps/angular/projects/ordering/src/pages/dashboard/components/payments-chart/payments-chart.component.ts
> +        text: 'Payment Methods',
text need translation

2022-05-11 14:24 UTC, merged