Removed OrderStatus table and added it as a column
abpframework/eShopOnAbp pull request #95
Opened 2022-03-17 13:18 UTC by malikmasis

Returned back enum approach instead of Enumeration

2022-03-17 14:16 UTC, enisn commented
We should change `OrderStatus` property type to `OrderStatus` from `string` for Entity and DTO.

JSON Serializer should serialize and deserialize it as string, and Entity Framework should store it as string. In the code, it should be enum type, otherwise, there is no meaning to make it an enum.

```csharp
.HasConversion(new EnumToStringConverter<OrderStatus>())
```

2022-03-17 20:08 UTC, enisn requested changes
We should change OrderStatus property type in DTO to OrderStatus enum and configure json serializer to handle string as enum.

https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-6.0

https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Converters_StringEnumConverter.htm

2022-03-17 20:08 UTC, enisn commented on services/ordering/src/EShopOnAbp.OrderingService.Application.Contracts/Orders/OrderDto.cs
>      public string OrderStatus { get; set; }
```suggestion
    public OrderStatus OrderStatus { get; set; }
```

2022-03-17 20:08 UTC, enisn commented on services/ordering/src/EShopOnAbp.OrderingService.Application/Orders/OrderAppService.cs
> +            OrderStatus = order.OrderStatus.ToString(),
.ToString() won't be required when we change type in dto
```suggestion
            OrderStatus = order.OrderStatus,
```

2022-03-18 06:37 UTC, enisn approved these changes

2022-03-18 08:01 UTC, gterdem commented on services/ordering/src/EShopOnAbp.OrderingService.EntityFrameworkCore/Migrations/20220317123922_RemovedOrderStatusTable.cs
> +    public partial class RemovedOrderStatusTable : Migration
When naming migrations or database interactions from code view; lets refer as `Entity` instead of _Table_.

2022-03-18 08:03 UTC, gterdem approved these changes

2022-03-18 08:03 UTC, merged